In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
plt.rcParams['figure.figsize'] = [16, 10]

In [3]:
train_df = pd.read_csv('Train.csv')
y = train_df.iloc[:,3]
test_df = pd.read_csv('Test.csv')
z = test_df.iloc[:, 0]
train_df.head()

,ward,total_households,total_individuals,target,dw_00,dw_01,dw_02,dw_03,dw_04,dw_05,...,pw_03,pw_04,pw_05,pw_06,pw_07,pw_08,ADM4_PCODE,lat,lon,NL
0,41601001: Ward 1,1674.45058,5888.20750,16.773757,0.933841,0.000846,0.005490,0.000676,0.000000,0.001372,...,0.002848,0.007537,0.000000,0.012928,0,0,ZA4161001,-29.682270,24.734743,0.292039
1,41601002: Ward 2,1736.99230,6735.33812,21.496661,0.696940,0.001253,0.004402,0.000000,0.002301,0.001323,...,0.014566,0.057127,0.019092,0.004131,0,0,ZA4161002,-29.119311,24.757737,3.207775
2,41601003: Ward 3,2403.57591,7273.04995,10.931425,0.810545,0.004517,0.008891,0.003986,0.007735,0.000956,...,0.057560,0.010358,0.001421,0.040881,0,0,ZA4161003,-29.142276,25.094093,0.000000
3,41601004: Ward 4,1740.78737,5734.49046,23.119257,0.659914,0.000000,0.006129,0.000000,0.000813,0.037245,...,0.000000,0.000669,0.000000,0.005011,0,0,ZA4161004,-29.372052,24.942867,2.038778
4,41601005: Ward 5,1730.51451,6657.23835,13.652252,0.950575,0.000655,0.001473,0.000598,0.006999,0.000818,...,0.004859,0.001290,0.000673,0.017629,0,0,ZA4161005,-29.409381,25.290165,0.000000

In [4]:
train_df = train_df.drop(columns=['ADM4_PCODE', 'ward', 'target'])
test_df = test_df.drop(columns=['ADM4_PCODE', 'ward'])

In [5]:
print(train_df.shape, test_df.shape)

(2822, 60) (1013, 60)

In [6]:
train_df.head(10)

,total_households,total_individuals,dw_00,dw_01,dw_02,dw_03,dw_04,dw_05,dw_06,dw_07,...,pw_02,pw_03,pw_04,pw_05,pw_06,pw_07,pw_08,lat,lon,NL
0,1674.45058,5888.20750,0.933841,0.000846,0.005490,0.000676,0.000000,0.001372,0.005750,0.031466,...,0.019968,0.002848,0.007537,0.000000,0.012928,0,0,-29.682270,24.734743,0.292039
1,1736.99230,6735.33812,0.696940,0.001253,0.004402,0.000000,0.002301,0.001323,0.007575,0.123547,...,0.018946,0.014566,0.057127,0.019092,0.004131,0,0,-29.119311,24.757737,3.207775
2,2403.57591,7273.04995,0.810545,0.004517,0.008891,0.003986,0.007735,0.000956,0.006686,0.022632,...,0.083010,0.057560,0.010358,0.001421,0.040881,0,0,-29.142276,25.094093,0.000000
3,1740.78737,5734.49046,0.659914,0.000000,0.006129,0.000000,0.000813,0.037245,0.005255,0.068909,...,0.002689,0.000000,0.000669,0.000000,0.005011,0,0,-29.372052,24.942867,2.038778
4,1730.51451,6657.23835,0.950575,0.000655,0.001473,0.000598,0.006999,0.000818,0.004985,0.009150,...,0.009699,0.004859,0.001290,0.000673,0.017629,0,0,-29.409381,25.290165,0.000000
5,1956.16888,6340.05782,0.766832,0.000579,0.005874,0.000000,0.000000,0.001448,0.038808,0.090013,...,0.027496,0.020771,0.002275,0.024184,0.039423,0,0,-29.126870,25.410360,1.464541
6,1966.40293,6230.77491,0.908400,0.006857,0.002941,0.000576,0.000720,0.001905,0.038519,0.012672,...,0.032712,0.003827,0.000509,0.002542,0.020192,0,0,-29.640860,26.091774,0.821738
7,2214.44168,6873.93123,0.890079,0.004549,0.002262,0.001151,0.000512,0.001805,0.009493,0.066842,...,0.022997,0.006364,0.001279,0.000526,0.025246,0,0,-30.029163,25.917164,0.000000
8,2022.95917,6736.49015,0.912298,0.002799,0.003688,0.000560,0.001260,0.000560,0.005770,0.024087,...,0.008259,0.006109,0.001276,0.000000,0.008791,0,0,-30.462176,26.133170,0.000000
9,1775.53323,5682.10110,0.882665,0.005227,0.009128,0.000000,0.003687,0.002839,0.024813,0.027002,...,0.002110,0.002644,0.000000,0.000583,0.002073,0,0,-30.420421,25.351630,0.000000

In [7]:
# concat the two datasets
df = [train_df, test_df]
df = pd.concat(df, keys=['x', 'y'], sort=False)
df.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 3835 entries, (x, 0) to (y, 1012)
Data columns (total 60 columns):
total_households     3835 non-null float64
total_individuals    3835 non-null float64
dw_00                3835 non-null float64
dw_01                3835 non-null float64
dw_02                3835 non-null float64
dw_03                3835 non-null float64
dw_04                3835 non-null float64
dw_05                3835 non-null float64
dw_06                3835 non-null float64
dw_07                3835 non-null float64
dw_08                3835 non-null float64
dw_09                3835 non-null float64
dw_10                3835 non-null float64
dw_11                3835 non-null float64
dw_12                3835 non-null float64
dw_13                3835 non-null float64
psa_00               3835 non-null float64
psa_01               3835 non-null float64
psa_02               3835 non-null float64
psa_03               3835 non-null float64
psa_04               3835 non-null float64
stv_00               3835 non-null float64
stv_01               3835 non-null float64
car_00               3835 non-null float64
car_01               3835 non-null float64
lln_00               3835 non-null float64
lln_01               3835 non-null float64
lan_00               3835 non-null float64
lan_01               3835 non-null float64
lan_02               3835 non-null float64
lan_03               3835 non-null float64
lan_04               3835 non-null float64
lan_05               3835 non-null float64
lan_06               3835 non-null float64
lan_07               3835 non-null float64
lan_08               3835 non-null float64
lan_09               3835 non-null float64
lan_10               3835 non-null float64
lan_11               3835 non-null float64
lan_12               3835 non-null float64
lan_13               3835 non-null float64
lan_14               3835 non-null float64
pg_00                3835 non-null float64
pg_01                3835 non-null float64
pg_02                3835 non-null float64
pg_03                3835 non-null float64
pg_04                3835 non-null float64
lgt_00               3835 non-null float64
pw_00                3835 non-null float64
pw_01                3835 non-null float64
pw_02                3835 non-null float64
pw_03                3835 non-null float64
pw_04                3835 non-null float64
pw_05                3835 non-null float64
pw_06                3835 non-null float64
pw_07                3835 non-null float64
pw_08                3835 non-null float64
lat                  3835 non-null float64
lon                  3835 non-null float64
NL                   3835 non-null float64
dtypes: float64(60)
memory usage: 1.8+ MB

In [8]:
# to see the variable discription
var_desc = pd.read_csv('variable_descriptions.csv')
pd.set_option('display.max_colwidth', 200) # So that we can see the full descriptions
var_desc

,Column,Description,Unnamed: 2,Unnamed: 3
0,dw_00,Percentage of dwellings of type: House or brick/concrete block structure on a separate stand or yard or on a farm,NaN,NaN
1,dw_01,Percentage of dwellings of type: Traditional dwelling/hut/structure made of traditional materials,NaN,NaN
2,dw_02,Percentage of dwellings of type: Flat or apartment in a block of flats,NaN,NaN
3,dw_03,Percentage of dwellings of type: Cluster house in complex,NaN,NaN
4,dw_04,Percentage of dwellings of type: Townhouse (semi-detached house in a complex),NaN,NaN
5,dw_05,Percentage of dwellings of type: Semi-detached house,NaN,NaN
6,dw_06,Percentage of dwellings of type: House/flat/room in backyard,NaN,NaN
7,dw_07,Percentage of dwellings of type: Informal dwelling (shack,in backyard),NaN
8,dw_08,Percentage of dwellings of type: Informal dwelling (shack,not in backyard,e.g. in an informal/squatter settlement or on a farm)
9,dw_09,Percentage of dwellings of type: Room/flatlet on a property or larger dwelling/servants quarters/granny flat,NaN,NaN
10,dw_10,Percentage of dwellings of type: Caravan/tent,NaN,NaN
11,dw_11,Percentage of dwellings of type: Other,NaN,NaN
12,dw_12,Percentage of dwellings of type: Unspecified,NaN,NaN
13,dw_13,Percentage of dwellings of type: Not applicable,NaN,NaN
14,psa_00,Percentage listing present school attendance as: Yes,NaN,NaN
15,psa_01,Percentage listing present school attendance as: No,NaN,NaN
16,psa_02,Percentage listing present school attendance as: Do not know,NaN,NaN
17,psa_03,Percentage listing present school attendance as: Unspecified,NaN,NaN
18,psa_04,Percentage listing present school attendance as: Not applicable,NaN,NaN
19,stv_00,Percentage of households with Satellite TV: Yes,NaN,NaN
20,stv_01,Percentage of households with Satellite TV: No,NaN,NaN
21,car_00,Percentage of households with a car: Yes,NaN,NaN
22,car_01,Percentage of households with a car: No,NaN,NaN
23,lln_00,Percentage listing landline ownership as: Yes,NaN,NaN
24,lln_01,Percentage listing landline ownership as: No,NaN,NaN
25,lan_00,Percentage listing language as: Afrikaans,NaN,NaN
26,lan_01,Percentage listing language as: English,NaN,NaN
27,lan_02,Percentage listing language as: IsiNdebele,NaN,NaN
28,lan_03,Percentage listing language as: IsiXhosa,NaN,NaN
29,lan_04,Percentage listing language as: IsiZulu,NaN,NaN
30,lan_05,Percentage listing language as: Sepedi,NaN,NaN
31,lan_06,Percentage listing language as: Sesotho,NaN,NaN
32,lan_07,Percentage listing language as: Setswana,NaN,NaN
33,lan_08,Percentage listing language as: Sign language,NaN,NaN
34,lan_09,Percentage listing language as: SiSwati,NaN,NaN
35,lan_10,Percentage listing language as: Tshivenda,NaN,NaN
36,lan_11,Percentage listing language as: Xitsonga,NaN,NaN
37,lan_12,Percentage listing language as: Other,NaN,NaN
38,lan_13,Percentage listing language as: Unspecified,NaN,NaN
39,lan_14,Percentage listing language as: Not applicable,NaN,NaN
40,pg_00,Percentage in population group: Black African,NaN,NaN
41,pg_01,Percentage in population group: Coloured,NaN,NaN
42,pg_02,Percentage in population group: Indian or Asian,NaN,NaN
43,pg_03,Percentage in population group: White,NaN,NaN
44,pg_04,Percentage in population group: Other,NaN,NaN
45,lgt_00,Percentage using electricity for lighting,NaN,NaN
46,pw_00,Percentage with piped water access: Piped (tap) water inside dwelling/institution,NaN,NaN
47,pw_01,Percentage with piped water access: Piped (tap) water inside yard,NaN,NaN
48,pw_02,Percentage with piped water access: Piped (tap) water on community stand: distance less than 200m from dwelling/institution,NaN,NaN
49,pw_03,Percentage with piped water access: Piped (tap) water on community stand: distance between 200m and 500m from dwelling/institution,NaN,NaN
50,pw_04,Percentage with piped water access: Piped (tap) water on community stand: distance between 500m and 1000m (1km) from dwelling /institution,NaN,NaN
51,pw_05,Percentage with piped water access: Piped (tap) water on community stand: distance greater than 1000m (1km) from dwelling/institution,NaN,NaN
52,pw_06,Percentage with piped water access: No access to piped (tap) water,NaN,NaN
53,pw_07,Percentage with piped water access: Unspecified,NaN,NaN
54,pw_08,Percentage with piped water access: Not applicable,NaN,NaN
55,ADM4_PCODE,Code for linking row to ward in the wards shapefile,NaN,NaN
56,lat,Lattitude of the center point of the ward,NaN,NaN
57,lon,Longitude of the center point of the ward,NaN,NaN
58,NL,"Nightlights value for the area arounf (lat, lon)",NaN,NaN
59,target,Percentage of women head households with income under R19.6k out of total number of households,NaN,NaN

The percentage dwellings can be grouped into rural and urban
Rural- dw_00, dw_01, dw_07, dw_08, dw_10
Urban- dw_02, dw_03, dw_04, dw_05, dw_06, dw_09
Other- dw_11, dw_12, dw_13

Percentage of household that could and could'nt afford schooling can be grouped into poor and not_poor
Poor- psa_00
Not_poor- psa_01
Other- psa_02, psa_03, psa_04

In [9]:
df.shape

(3835, 60)

In [10]:
df.isnull().sum()

total_households     0
total_individuals    0
dw_00                0
dw_01                0
dw_02                0
dw_03                0
dw_04                0
dw_05                0
dw_06                0
dw_07                0
dw_08                0
dw_09                0
dw_10                0
dw_11                0
dw_12                0
dw_13                0
psa_00               0
psa_01               0
psa_02               0
psa_03               0
psa_04               0
stv_00               0
stv_01               0
car_00               0
car_01               0
lln_00               0
lln_01               0
lan_00               0
lan_01               0
lan_02               0
lan_03               0
lan_04               0
lan_05               0
lan_06               0
lan_07               0
lan_08               0
lan_09               0
lan_10               0
lan_11               0
lan_12               0
lan_13               0
lan_14               0
pg_00                0
pg_01                0
pg_02                0
pg_03                0
pg_04                0
lgt_00               0
pw_00                0
pw_01                0
pw_02                0
pw_03                0
pw_04                0
pw_05                0
pw_06                0
pw_07                0
pw_08                0
lat                  0
lon                  0
NL                   0
dtype: int64

In [11]:
df.columns

Index(['total_households', 'total_individuals', 'dw_00', 'dw_01', 'dw_02',
       'dw_03', 'dw_04', 'dw_05', 'dw_06', 'dw_07', 'dw_08', 'dw_09', 'dw_10',
       'dw_11', 'dw_12', 'dw_13', 'psa_00', 'psa_01', 'psa_02', 'psa_03',
       'psa_04', 'stv_00', 'stv_01', 'car_00', 'car_01', 'lln_00', 'lln_01',
       'lan_00', 'lan_01', 'lan_02', 'lan_03', 'lan_04', 'lan_05', 'lan_06',
       'lan_07', 'lan_08', 'lan_09', 'lan_10', 'lan_11', 'lan_12', 'lan_13',
       'lan_14', 'pg_00', 'pg_01', 'pg_02', 'pg_03', 'pg_04', 'lgt_00',
       'pw_00', 'pw_01', 'pw_02', 'pw_03', 'pw_04', 'pw_05', 'pw_06', 'pw_07',
       'pw_08', 'lat', 'lon', 'NL'],
      dtype='object')

In [12]:
train_df = df.loc['x']
test_df = df.loc['y']

In [13]:
print(train_df.shape, test_df.shape)

(2822, 60) (1013, 60)

In [14]:
X = train_df.iloc[:,:]

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [16]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)
train_df = sc.fit_transform(train_df
                           )

In [17]:
from catboost import CatBoostRegressor

cat_model = CatBoostRegressor(iterations=500,
                             learning_rate=0.05,    
                             verbose=False,
                             )
cat_model.fit(X_train, y_train)

In [18]:
cat_model.score(X_train, y_train)

0.9779923498526911

In [19]:
# calculate mean absolute error
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

pred = cat_model.predict(X_test)
mae = mean_absolute_error(pred, y_test)
mse = mean_squared_error(pred, y_test)
r2 = r2_score(pred, y_test)

print(f'MAE: {mae} \nMSE: {mse} \nR2: {r2}')

MAE: 2.6099425083396013
MSE: 12.445666952964872
R2: 0.8737227683345358

In [ ]:
import xgboost as xgb

xgb_model = xgb.XGBClassifier()
xgb_model.fit(X_train, y_train)

MAE: 2.6215903187956986 
MSE: 12.522044291486523 
R2: 0.8780787013703247

In [20]:
predictions = cat_model.predict(test_df)
prediction = pd.DataFrame(predictions)
prediction.index = z
prediction.index.name = 'ward'
prediction.columns=['target']
prediction.to_csv('pred3.csv')